version: '3.4'

services:
  story.host:
    image: ${DOCKER_REGISTRY-}storyhost
    build:
      context: .
      dockerfile: src/Story.Host/Dockerfile
    environment:
      - ConnectionStrings__Redis=redis
      - StoryAngularAppUrl=http://story.angular.app:4200
    depends_on:
      - redis
      - story.angular.app

  story.angular.app:
    image: ${DOCKER_REGISTRY-}storyangularapp
    build:
      context: .
      dockerfile: src/Story.Host/ClientApp/Dockerfile
    volumes:
      - ./src/Story.Host/ClientApp:/app

  redis:
    image: redis