version: '3.4'

services:
  questionnaire.host:
    image: ${DOCKER_REGISTRY-}questionnairehost
    build:
      context: .
      dockerfile: src/Questionnaire.Host/Dockerfile
    environment:
      - ConnectionStrings__Redis=redis
      - QuestionnaireAngularAppUrl=http://questionnaire.angular.app:4200
    depends_on:
      - redis
      - questionnaire.angular.app

  questionnaire.angular.app:
    image: ${DOCKER_REGISTRY-}questionnaireangularapp
    build:
      context: .
      dockerfile: src/Questionnaire.Host/ClientApp/Dockerfile
    volumes:
      - ./src/Questionnaire.Host/ClientApp:/app

  redis:
    image: redis