version: '3.4'

services:
  story.host:
    image: ${DOCKER_REGISTRY-}storyhost
    build:
      context: .
      dockerfile: src/Story.Host/Dockerfile
    environment:
      - ConnectionStrings__Redis=redis
    depends_on:
      - redis

  story.angular.app:
    image: ${DOCKER_REGISTRY-}storyangularapp
    build:
      context: .
      dockerfile: src/Story.Host/ClientApp/Dockerfile
    ports:
      - "4200:4200" 
      - "49153:49153"
    volumes:
      - ./src/Story.Host/ClientApp:/app

  redis:
    image: redis